name: lecture-python-programming
channels:
  - conda-forge
dependencies:
  - python=3.8
  - anaconda=2020.11
  - pip
  - pip:
    - jupyter-book
    - sphinxext-rediraffe
    - sphinx-multitoc-numbering
    - joblib
    - interpolation
    - sphinx-tojupyter
    - quantecon-book-theme

