name: lecture-python-programming
channels:
  - default
dependencies:
  - python=3.8
  - anaconda=2020.07
  - pip
  - pip:
    - jupyter-book
    - sphinxext-rediraffe
    - sphinx-multitoc-numbering
    - joblib
    - interpolation
    - sphinx-tojupyter
    - quantecon-book-theme

